name: horizontal_tree_selector
description: A Flutter horizontal multi-level tree selector widget. 一个横向多级树形结构选择器组件，支持无限层级数据选择。
version: 0.0.2
homepage: https://github.com/symboy/horizontal_tree_selector
repository: https://github.com/symboy/horizontal_tree_selector
issue_tracker: https://github.com/symboy/horizontal_tree_selector/issues

topics:
  - widget
  - selector
  - tree
  - picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
